# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('logged_in', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('token', models.IntegerField()),
                ('status', models.IntegerField()),
                ('t_type', models.IntegerField()),
                ('done', models.IntegerField(default=0)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstparty', to='credit.Member')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectparty', to='credit.Member')),
            ],
        ),
    ]
